name: GuitarAccuracy
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    macOS: '14.0'
settings:
  base:
    SWIFT_VERSION: 5.9
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    PRODUCT_BUNDLE_IDENTIFIER: com.howieh.GuitarAccuracy
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    CODE_SIGN_ENTITLEMENTS: GuitarAccuracy.entitlements
  configFiles:
    Debug: Configurations/Debug.xcconfig
    Release: Configurations/Release.xcconfig
packages: {}
targets:
  GuitarAccuracy:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: GuitarAccuracy
        MACOSX_DEPLOYMENT_TARGET: 14.0
    scheme:
      testTargets:
        - GuitarAccuracyTests
        - GuitarAccuracyUITests
      gatherCoverageData: true
  GuitarAccuracyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/Unit
    dependencies:
      - target: GuitarAccuracy
  GuitarAccuracyUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Tests/UITests
    dependencies:
      - target: GuitarAccuracy
